### ISSUE TITLE
Aid

### ISSUE THREAD

**Issue by git-kor-av** [DFreds/dfreds-convenient-effects#1]
As part of the Aid effect, I don't think you should be applying both temporary HP and Max HP.  It has a strange effect where the temp HP are not removed because the effect is "semi-permanent".  Aid should increase Max HP and essentially "heal" the same amount of HP that it's increasing Max by, however I don't think that can be done in the scope of an Active Effect.

On a separate note:  Seriously awesome module!  I've been wanting something like this for a while now.  The structure to add effects seems pretty simple (wondering how hard it would be to add an interface for adding new effects).

**Comment by DFreds** [comment]
Ah, that is a fantastic point I did not consider. I actually think I could heal for 5 HP instead of doing temp HP, but as you said, it would be outside of the active effect. My only concern would be that if you didn't lose any HP after the 8 hour expiration and were at the max + 5 total HP, would you then have more HP than you're allowed to have on the expiration? I'll have to test it.

I'm glad you're enjoying the module! Adding your own effects is a goal for a few versions in the future. Stay tuned!

**Comment by DFreds** [comment]
Minor update on this, it's a bit more challenging than I thought. While I can easily increase the max HP and current HP, I was attempting to also return the effected actor's HP back to their normal max if they would be above it when the effect expires. Stay tuned, but this will take a little longer.

**Comment by krysztalzg** [comment]
I will allow myself to jump onto this thread as Aid effect is completely broken. Your effect adds +5 to the current HP, and with the Active Effect logic it adds it every time the value changes. So if I do -5 do deal 5 damage, it does nothing because effect formula also adds 5 at the same time.

**Comment by DFreds** [comment]
Yeah, this is super broken. Even if I change it back to just increasing temp HP, it still does this auto adding to the value. I think I'm going to remove Aid for the time being until I can figure out a better solution.

**Comment by DFreds** [comment]
Remove in v1.6.0. I'll add it back when I can fix the issue

**Comment by DFreds** [comment]
Finally fixed, and added to v1.7.0
