### ISSUE TITLE
Rage is doubled

### ISSUE THREAD

**Issue by Berytak** [DFreds/dfreds-convenient-effects#102]
Hey there!
When using Rage on a Barbarian the effect is doubled.

![image](https://user-images.githubusercontent.com/85394657/148503658-e5a61ec7-82a3-48cf-9946-be27e43c8ef8.png)

The chat states also both effects.

![image](https://user-images.githubusercontent.com/85394657/148503750-e111f07b-f0ea-43e1-93a8-9e0e5c8f6b5f.png)

This is what's going on in the console.

![image](https://user-images.githubusercontent.com/85394657/148503887-3e6c9f34-a152-4993-99fe-bb35e20669fe.png)

At this point I'm using the latest stable FoundyVTT build and have only activated the following modules for testing puprose.

![image](https://user-images.githubusercontent.com/85394657/148504118-e0f6ecae-44a8-466e-a3c7-b6c42605eb24.png)

And at last the module configuration.

![image](https://user-images.githubusercontent.com/85394657/148504290-7214be9c-aa26-4a61-b7f4-a6259682ac39.png)

I'm not a programmer, but imho it seems that DAE and Conveniant Effects are applying the rage condition. Everything else seems to work as intended, but I have no clue why only this effect is doubled.

Thanks in advance!

Cheers!
Berytak

**Comment by DFreds** [comment]
Does the item "Rage" on the actor itself have an effect attached to it?

**Comment by Berytak** [comment]
Yes, both have effects attached. 

![image](https://user-images.githubusercontent.com/85394657/148569328-c4971be6-f8c6-41e3-bb89-d886d24b0fff.png)

And those are the effects under the effects tab. The upper one ist the DEA and the lower one the conveniant effect.

![image](https://user-images.githubusercontent.com/85394657/148569117-900133a5-7df1-4f46-9f5a-6650c8bde8e9.png)

**Comment by DFreds** [comment]
Okay, so what is likely happening is that you have Midi-QoL auto applying matching Convenient Effects. So when a player uses "Rage", it is searching for the Rage condition in Convenient Effects and automatically applying it. However, the Rage feature on that player also has an effect defined, so using it also applies the effect defined on the Rage feature on that actor.

Assuming I'm correct, you can solve this in two ways:

1. Delete the effect on the Rage feature on the actor. This will make it so that only the Convenient Effect is used. I recommend this option because I do some special stuff to handle rage based on the barbarian level without you having to do anything.
2. Check the "Don't apply Convenient Effect" in the details of the Rage feature on that actor. This will make it so only the effect defined on the Rage feature will be applied.

Let me know if that fixes it.

**Comment by Berytak** [comment]
> Okay, so what is likely happening is that you have Midi-QoL auto applying matching Convenient Effects. So when a player uses "Rage", it is searching for the Rage condition in Convenient Effects and automatically applying it. However, the Rage feature on that player also has an effect defined, so using it also applies the effect defined on the Rage feature on that actor.
> 
> Assuming I'm correct, you can solve this in two ways:
> 
> 1. Delete the effect on the Rage feature on the actor. This will make it so that only the Convenient Effect is used. I recommend this option because I do some special stuff to handle rage based on the barbarian level without you having to do anything.
> 2. Check the "Don't apply Convenient Effect" in the details of the Rage feature on that actor. This will make it so only the effect defined on the Rage feature will be applied.
> 
> Let me know if that fixes it.

That did it for me. I deleted the Rage feature from the char and just pulled it from the SRD compendium again. Now everything seems to work as intended. I guess this had something to do with the D&D Beyond Importer module from MrPrimate. There is an option where you can create new effects instead of pulling them from existing ones. I think I had this option checked while importing the characters because the AC calculation was wonky.
Nevertheless, I couldn't have solved this on my own.

Thank you very much, I apprechiate your help!

Cheers!
Berytak

**Comment by DFreds** [comment]
Glad it worked!
