### ISSUE TITLE
Suggestion: Ability to choose which effects to include on Token HUD

### ISSUE THREAD

**Issue by GebotheBardbarian** [DFreds/dfreds-convenient-effects#13]
The ability to replace the  default Token Status Effects with your convenient effects is amazing.

I would suggest a feature to allow the user to designate which effects from the full module list they want to be included on the Token HUD list. For example, including Bless and Bane.

This would be potentially useful especially for DMs, like myself, who run a relatively low automation game.

Perhaps a right-click context menu option that toggles, similarly to the Favorites feature?

**Comment by DFreds** [comment]
I was thinking of just including things you've Favorited in the lists and letting you choose if you wanted those included, but your idea might be better. I'll think about the use case a bit and implement something. Good idea!

**Comment by asimone** [comment]
+1 for this, I'd particularly love to add effects that DON'T have automation. Sometimes it's useful to have a reminder marker of some kind or another without worrying about an automated effect being applied. 

Hunter's Mark comes to mind, I don't actually want roll automation there, I just want to remember which creature the player marked. 

In theory, you can do that be simply "adding" rather than "replacing" with your effects, but when I replace, I lose EVERYTHING and _only_ your automated effects remain.

**Comment by DFreds** [comment]
This is fixed in version 1.6.0.
