### ISSUE TITLE
Feature request: Edit Stock effects

### ISSUE THREAD

**Issue by samstork** [DFreds/dfreds-convenient-effects#139]
Hello DFreds, 

I love the module, it has been a great help in my games. However, being a token magic FX, homebrew, and houserule aficionado, I see myself often changing stuff to suit my needs. Duplicating and editing effects does the job, but it sees my Custom folder bloat quite rapidly. 

So my request would be to enable editing of stock effects. My suggestion would be to add a toggle in the module settings. 

Adding subfolders as others have suggested would already alleviate my concerns. 

Kind regards, 
Samuel Stork

**Comment by brandonhinds** [comment]
I second this. I make a lot of my own effects, and not being able to disable the defaults that come with this module lead to some undesirable effects.

For example, I have multiple players with the Shield spell, and I want to give each of them their unique animation for it. Unfortunately this module is detecting this and displaying the (in my opinion) ugly blue bubble along with my own animations.

**Comment by GhostwheelX** [comment]
Third'ed, I'd like to fix some of the effects that haven't been touched in a while (reckless attack, heroism, aid) so that they auto-apply the correct effect in my games, and this would be a good way to do so without having to wait for the original source code to be changed, or for me to have my own version of specific effects (for example, my version of the Shield spell is a little different from the original version).

**Comment by DFreds** [comment]
> I think having a global toggle on all animations would be a great change, however my JavaScripting isn't good enough to implement a toggle like that cleanly. Would it be an if statement that checks against a global flag for every instance of the tokenMagicChanges?

This is already a setting.

**Comment by DFreds** [comment]
The hesitation around this request is in regards to ease of use for most users and ease of maintenance on my end. Allowing users to edit stock effects makes the possibility of user error extremely high for the average user without a good way to undo their changes if an update gets pushed that fixes a stock effect.

One potential solution for this would be to make duplicated effects take the place of the stock effects and potentially add an icon that shows that. So instead of duplicating Shield and it appearing in Custom effects, it would still appear under Spells but have an icon indicating it was a custom one. Then you could potentially "delete" the custom one which could revert it back to the stock one.

I also think that implementing custom folders (#107) as you mentioned would be helpful in regards to organization, but that is still coming.

**Comment by brandonhinds** [comment]
> This is already a setting.

Apologies, I must have missed this. Let me look back over the module settings again.

> One potential solution for this would be to make duplicated effects take the place of the stock effects and potentially add an icon that shows that. So instead of duplicating Shield and it appearing in Custom effects, it would still appear under Spells but have an icon indicating it was a custom one. Then you could potentially "delete" the custom one which could revert it back to the stock one.

I think this approach is good - both the icon and the ability to roll back to the default effect. You can put a warning around the consequences of changing the default animations (i.e. you're on your own), but I don't think you need to do much more.

**Comment by samstork** [comment]
A lot of other modules implement compendiums of stock items one can use. Perhaps having a compendium of the stock effects would be another possible solution to the rollback issue. However I do not know if that would be possible from a technical standpoint.

**Comment by DFreds** [comment]
> A lot of other modules implement compendiums of stock items one can use. Perhaps having a compendium of the stock effects would be another possible solution to the rollback issue. However I do not know if that would be possible from a technical standpoint.

Yeah, it's actually not possible to have a true compendium of effects as Foundry defines a compendium. I have asked for that restriction to be lifted, but it seems like a deliberate choice by the Foundry devs to not allow that at the moment.

**Comment by GhostwheelX** [comment]
Any update on this by any chance? I'd like to try out the way the new grappled condition from the 5.5e playtest pamphlet works at my table (basically just add an OverTime effect to the existing condition), but I can't add it to the normal grappled condition.

**Comment by thatlonelybugbear** [comment]
You could duplicate the grapple condition as Custom and change what you want!

**Comment by DFreds** [comment]
@GhostwheelX what @thatlonelybugbear said. I might add a setting that will hide the original effect if a custom one overrides it. But that would be a separate thing
