### ISSUE TITLE
Am I the only one getting his Custom effects deleted ? 

### ISSUE THREAD

**Issue by Steelskinz** [DFreds/dfreds-convenient-effects#165]
**Describe the bug**
My Customs effects keep getting deleted 
**To Reproduce**
I got no idea of how this happen, but sometimes when I come back they're just no where to be found.

**Expected behavior**
Well to not delete every custom things i've made ? 
**Screenshots**

**Additional context**
I am hosting on Oracle Cloud. 
We've tried with the community to reproduce the behavior by creating a new world with only that module, creating an effect and trying to make it happens. Nothing. I created another world and put every modules that I had on my original one as suggested by the community, but nothing happened either. 
My version of Foundry is : 9.269
I'm using : Dnd5e 1.6.3
Module version : Last one to date.

Found the issue, and I don't understand why it's working this way. 
![image](https://user-images.githubusercontent.com/93941729/184951808-e88d4a45-4f56-473e-9f3d-7777326f28a9.png)
So it seems where you create for the first time a custom effect and **ITEM** names Custom Convenient Effects is created and if this one is deleted, everything you're created is gone too. Why is this working this way ? Or not even written in the description of the module ? 

So I tried to reinstall clearly the module and this kept appearing, however when I tried to move it in a "Not delete" folder I have, it disappeared, leaving nothing but stuggle behind it. I don't know if it's fixed but for now it seems to work correctly ? 

The issue here was that I, somehow, managed to delete that file that serve as a database.
Ah yes, when I moved the item somewhere it disappeared like it should have from the beginning, So might have been just a random bug.

**Comment by DFreds** [comment]
Foundry defines ActiveEffects as things that can only exist on an Item or a Character. Thus, this module creates an item behind the scenes and adds all of the effects you create to it. It then hides this item from your list of items to not clutter anything up. It's not explicitly stated that it's doing this anywhere because it shouldn't matter from the user perspective.

Somewhere along the line, your original Custom Convenient Effect item was deleted. I don't know how you did that or why it might have happened... Also, I thought I had code around this to handle when it happens, so I'll double check it. But yeah, I have no other answer for you because I've never seen it happen and you're the only one who has reported it.

My only real suggestion at the moment would be to delete the entry in the settings.db for the world about Convenient Effects to reset all of Convenient Effect's settings. Hopefully, that resets the item ID it was using to determine what item to use to store effects.

I'll close this if I find that deleting the custom effect is handled correctly.

**Comment by thatlonelybugbear** [comment]
Could it happen with a macro deleting items maybe not in folders or something like that?

**Comment by Steelskinz** [comment]
> Foundry defines ActiveEffects as things that can only exist on an Item or a Character. Thus, this module creates an item behind the scenes and adds all of the effects you create to it. It then hides this item from your list of items to not clutter anything up. It's not explicitly stated that it's doing this anywhere because it shouldn't matter from the user perspective.
> 
> Somewhere along the line, your original Custom Convenient Effect item was deleted. I don't know how you did that or why it might have happened... Also, I thought I had code around this to handle when it happens, so I'll double check it. But yeah, I have no other answer for you because I've never seen it happen and you're the only one who has reported it.
> 
> My only real suggestion at the moment would be to delete the entry in the settings.db for the world about Convenient Effects to reset all of Convenient Effect's settings. Hopefully, that resets the item ID it was using to determine what item to use to store effects.
> 
> I'll close this if I find that deleting the custom effect is handled correctly.

You can close it, everything is working fine now and I got no more weird items going around in my folders. 


> Could it happen with a macro deleting items maybe not in folders or something like that?

It might be the case. I did a clean up before this actually happen, didn't expect it to be the issue. Well, it was all my fault at first, i'll stop tweaking weird stuff again haha
