### ISSUE TITLE
[Request] allow gm to set permission to allow players to create/modify effects

### ISSUE THREAD

**Issue by Mizzajl** [DFreds/dfreds-convenient-effects#195]
I have tried giving my players full permission to everything but they still cannot create/modify or duplicate as custom for the effects.

![image](https://user-images.githubusercontent.com/31535978/205918718-8824243b-20ed-4c94-af97-23ac8b22d5ca.png)

**Comment by DFreds** [comment]
Ah, this is an interesting issue. It's because the underlying item that holds the effects probably doesn't have player permission. The item is automatically hidden in the items directory. 

I added a new setting to fix this: https://github.com/DFreds/dfreds-convenient-effects/wiki/User-Guide#allow-player-custom-effects

Should be out in the next minor release
