### ISSUE TITLE
Enlarge reduce doesn't actually increase token size anymore

### ISSUE THREAD

**Issue by SirAron111** [DFreds/dfreds-convenient-effects#201]
Enlarge reduce effect doesn't actually increase or decrease token size anymore. I remember it doing so and even had a copy of it working for my player's rune night fighter to up and down his size when needed. But for some reason since a few updates ago it doesn't work anymore. Is there a custom flag I am missing or so to increase token size with effects. (up the dimensions from with 1 hight 1 to with 2 hight 2 etc)

So is there a list of the various flags and bonuses with a description of what they do for building custom effects?
For example, I was trying to make an effect that works like aid but with higher hp than 5 and if i make a copy of the aid effect, the copy doesn't have any effects added so I can't just increase the numbers, so i don't know what to add to make it work.

**Comment by DFreds** [comment]
What actor did you try to enlarge? If the actor in question was small (like a halfling or gnome), it would go to medium which would still only be a 1x1 grid. Otherwise, medium to large will make them 2x2. 

I can't seem to reproduce this, so it might also have been an issue with ATE that has since been fixed. Not sure.
