### ISSUE TITLE
Possible bug with module Forien's Copy environment

### ISSUE THREAD

**Issue by Nedrapter** [DFreds/dfreds-convenient-effects#265]
Forien's Copy Environment allows you to copy module settings from one world to another. As I have more than 10 worlds, it's a vital module to not do the same work 10x. I have created custom convenient effects, about 20 of them. When I export the module settings with FCE and import them on a new world, not only the custom effects do not get copied (which sound like module settings to me), but also it removes any custom effects the world had. Even if both the new and old were exact same effects, they still get deleted.
I'm not sure if this requires some action from this side to be fixed or from FCE.

**Comment by DFreds** [comment]
I can't speak to what copy environment is doing, but the custom effects exist on a hidden Item. This is because active effects cannot exist outside the scope of an item or an actor. In the CE app, you can export all of them if you click the Custom folder, which will put out a json file. Then you can import it using the other button.

![image](https://github.com/DFreds/dfreds-convenient-effects/assets/11878569/04eab3d0-5a1e-4aca-b527-22bad0a3e1bb)
