### ISSUE TITLE
Movement effects aren´t really blocking token movement

### ISSUE THREAD

**Issue by spitfire1081** [DFreds/dfreds-convenient-effects#320]
When i set RESTRAINED to a token, the player is still able to move it.
I checked the DAE information and it appears to be ok, setting the movement to 0. The ruler integration shows red too, but the player still can move the token.

SOLUTION: the active effect prevents players to move or apply movement restriction rules when an effect is active.

**Comment by DFreds** [comment]
Yeah, it's not really the intention of the module to put that level of control onto tokens. Remember, all CE is doing is temporarily changing the data of an actor to let you keep track of things. For instance, you could simply go into a character sheet, set all their movement to 0 without any effects, and you'd still be able to move it around because it doesn't actually prevent anything from the user perspective. I also don't think it should, so I'm going to close this as out of scope for the module.

There might be other modules that do this that you could look into, but I don't know any offhand.
