### ISSUE TITLE
Chinese characters should not be ignored, Request to add support for Chinese characters.

### ISSUE THREAD

**Issue by yyzitai** [DFreds/dfreds-convenient-effects#342]
The characters used in the test are：
“a”
“第一个测试效果的效果a”
“第二个测试的效果”
“第三个测试的效果”

Watch the video

**Comment by yyzitai** [comment]
![222](https://github.com/user-attachments/assets/b29acf14-9035-4c30-963c-b266ce55e9f8)

https://github.com/user-attachments/assets/93a9d541-8ace-4492-b180-ff094c2607a7

**Comment by DFreds** [comment]
I don't have any idea how they're being ignored. Are they ignored in the sidebars for actors or items? I'm also not noticing which characters are ignored exactly based on your test. And why did you upload music? lol

**Comment by yyzitai** [comment]
The uploads are videos，Maybe github is not displaying correctly，Download mp4 may be able to watch。
According to my observation，the Convenient Effect lD is not compatible with Chinese characters。
At the same time, I am translating cn.json and hope to support Chinese in the future version。
Thank you for your hard work。
![3333](https://github.com/user-attachments/assets/bac49120-94ef-4eb4-89e5-1471c29329fb)

**Comment by yyzitai** [comment]
In addition, Dynamic cannot be modified in either edit or new mode. Is this a BUG?
![4444](https://github.com/user-attachments/assets/7cf6ae05-6bec-4406-98a4-9165fe9af722)

**Comment by BrotherSharper** [comment]
@DFreds 
Hello, so it seems that when a convenient effect is created, effects that only contain special characters (in this case Chinese and Japanese and what not) are not considered when the ID is created.

As such, they all end up with the same ID, and thus they apply the very first of its ID when selected or when trying to open.
Example:

Blinded in Japanese is "盲目状態", gives the convenient effect id of `ce-`
Prone in Japanese is "伏せ状態", gives the convenient effect id of `ce-`

Since they are the same, if you try to open either, you only get one of them, whichever was created later.
As we are unable to change the convenient effect ID on our own, this renders convenient effects unusable for languages that do not primarily use alphabetical letters.

I believe this is what this issue is trying to say. 
I'd say that the severity of this is extremely critical.

**Comment by BrotherSharper** [comment]
Just to add to this, it happens with both custom ones and the localized names since convenient effect ID is qual to `ce-`+`name of the effect` which render any additions of languages with special characters impossible

**Comment by DFreds** [comment]
Related to #349, closing here
