### ISSUE TITLE
Module not showing up

### ISSUE THREAD

**Issue by yahavatar** [DFreds/dfreds-convenient-effects#4]
I've installed your module on my server hosted at The Forge. Running 0.8.6 and D&D5e 1.3.3. I see that your module is installed and enabled:

![image](https://user-images.githubusercontent.com/780527/121386189-cadf6180-c917-11eb-9fed-57b05d6074b2.png)

However, I can't seem to locate the icon:

![image](https://user-images.githubusercontent.com/780527/121386304-e21e4f00-c917-11eb-8148-54015167dcef.png)

And, I see no settings:

![image](https://user-images.githubusercontent.com/780527/121386354-ea768a00-c917-11eb-9bf9-cfc679727302.png)

I'm willing to admit the problem is most likely a user error on my part, but I thought I'd post it here in case it is a module issue.

Thanks,
yah.

**Comment by DFreds** [comment]
That usually happens when there is an error and the module failed to load. I just double checked everything on my end and it seems fine. Can you check if there are any errors in your console?

1. Press F12
2. Click 'Console'
3. Click the Red error icon

You could also just try uninstalling and reinstalling it.

**Comment by DFreds** [comment]
No problem. I appreciate you taking the time to be sure, because that would be a catastrophic bug on my end if that happened 😄
