### ISSUE TITLE
Barkskin not increasing AC

### ISSUE THREAD

**Issue by Avitale34** [DFreds/dfreds-convenient-effects#46]
**Describe the bug**
I am trying to use the Barkskin buff but it does not seem to be doing anything to my druid it just keeps his AC at 12.

**To Reproduce**
1. apply barkskin

**Expected behavior**
Increases to 16 if not better.

**Screenshots**
![image](https://user-images.githubusercontent.com/65961637/130648896-0e2b369c-f086-4229-9bb6-c6e3d0776b77.png)

**Comment by thatlonelybugbear** [comment]
Hey. Just make sure that you have not set a Flat AC and use something like Equipped of Natural Armor on the configure Armor on the AC icon on the character sheet.
Barkskin works fine for me, Foundry 0.8.9, DAE 0.8.44, DFreds CE 1.9.2, Dnd5E 1.4.2

**Comment by Avitale34** [comment]
He is currently set to equipped armor, is that not what it should be?

**Comment by Avitale34** [comment]
Using DAE 8.45 Foundry 8.9 Dfreds 1.9.2 DND5e 1.4.2

**Comment by thatlonelybugbear** [comment]
DAE 8.45 breaks some things as far as I know. Might be a good idea to
downgrade to .44 and check again.
https://discord.com/channels/170995199584108546/722566083499786352/879681749997744138

**Comment by DFreds** [comment]
Thanks @thatlonelybugbear. I'll look at it more later to be sure. Might require a bug report on DAE if that is true.

@Avitale34 just make sure that when you open the armor config sheet, that there is no number in the big text box that you can delete. You'll see a number no matter what, but if it's calculated you won't actually be able to delete it (it's hint text). If there is a number there, it'll use that rather than calculate it. That's what @thatlonelybugbear was saying.

**Comment by thatlonelybugbear** [comment]
Don't think that DAE is to blame here in the end. Just updated to try it.

Probably what @DFreds explained better.

**Comment by Avitale34** [comment]
![image](https://user-images.githubusercontent.com/65961637/130688032-2234f20b-596b-4d39-8e39-75390452e5d1.png)

I don't have any number in there. So not sure what's going on.

**Comment by Avitale34** [comment]
Hmm I put a number in there and then deleted it and now it works lol.

**Comment by DFreds** [comment]
🤷‍♂️ glad it's fixed
