### ISSUE TITLE
Heroism and Regeneration not automated

### ISSUE THREAD

**Issue by GhostwheelX** [DFreds/dfreds-convenient-effects#62]
Now that we have the `Overtime` flag from midi-qol, might it be possible to entirely automate the Heroism and Regenerate spells using CE?

**Comment by DFreds** [comment]
I was able to add Regenerate, but Heroism is a bit more challenging as it relies on the caster's spellcasting ability modifier. Since CE is meant to be easy to apply without the need for targeting or midi or anything (although the option is there), I need to figure out the right way to ask the user for that information. It might be a simple dialog, but that could get annoying. Not sure yet

**Comment by DFreds** [comment]
Regeneration released in v1.12.0. I'm going to close this until I figure out a good way to do Heroism.
