### ISSUE TITLE
Minor Feature Request - Add effects management functions based on effect "id" and not on effect "name"

### ISSUE THREAD

**Issue by p4535992** [DFreds/dfreds-convenient-effects#63]
**Is your feature request related to a problem? Please describe.**

I am successfully using the functions to remove / add / control an effect through the API provided by the "effect-interface.js" class and everything seems to be fine, but there are cases where the effect name is something very vague and / or which can be confusing when different modules start to apply effects with the same name, but for different purposes.

In my specific case I recover two effects with the same name, where, however, one was created through my module and one through yours. Thanks to an applied flag I can distinguish the two effects and at this point I use the id of the effect to remove the correct one with the standard "deleteEmbeddedDocuments".

**Describe the solution you'd like**

A simple solution (at least for me),  is to add the same functions to the already existing functionalities for the effect name, but with the input parameter of the effect ID.

So add to the class "effect-interface.js" these functions:

async toggleEffect(effectId, ...uuids)
async hasEffectApplied(effectId, uuid)
async removeEffect(effectId, uuid)
async addEffect(effectId, uuid, origin)

**Describe alternatives you've considered**

For now i just use the standard embedded documents support like this:

```
/**
   * Removes the effect with the provided id from an actor
   *
   * @param {string} effectToRemove - the effect to remove
   * @param {string} actor - the actor to remove the effect from
   */
  async removeEffectFromId(effectToRemove: ActiveEffect, actor: Actor) {
    if (effectToRemove) {
      await actor.deleteEmbeddedDocuments('ActiveEffect', [<string>effectToRemove.id]);
      log(`Removed effect ${effectToRemove?.data?.label} from ${actor.name} - ${actor.id}`);
    }
  }
```

**Additional context**

**Comment by DFreds** [comment]
This should be doable. 

For my own notes:

First, tposney and midi can't support automatically adding/removing effects by ID because he can only work with the name of a feature or spell being used. I would need a standardized way to convert a name to an ID so that functionality doesn't break. A simple slugify type method should work.

Second, I can't define multiple functions with different arguments (ex: `toggleEffect(effectId, ...uuids)` and `toggleEffect(effectName, ...uuids)` and the like because it would be the same number of arguments and JS wouldn't be able to distinguish between them. I need a way to detect in a single method if an effect ID or an effect name was given, and find the effect correctly.

**Comment by p4535992** [comment]
Is this more easy to integrate now on v11 ?

**Comment by p4535992** [comment]
@DFreds If this is something you would be willing to consider I can open a PR about it.

**Comment by DFreds** [comment]
If you want to open a PR, feel free. I would ask for reviews in short bursts rather than all at once. Did something get added in v11 that would make this easier?

**Comment by DFreds** [comment]
v7.0.0 now includes a flag called `ceEffectId` which is the `ce-${effect.name.slugify()}`. This effect ID gets updated when the name changes, so not sure if this really solves this yet

**Comment by DFreds** [comment]
Closing due to the age of this issue though lol

**Comment by DFreds** [comment]
Actually, misunderstood. You can also use the actual `effect.id` now as well. So this is resolved
