### ISSUE TITLE
Effect for Hex

### ISSUE THREAD

**Issue by magroader** [DFreds/dfreds-convenient-effects#81]
**Is your feature request related to a problem? Please describe.**
My Warlock keeps casting Hex and I've got nothing for it!

**Describe the solution you'd like**
A hex icon!

**Describe alternatives you've considered**
I've been using "charmed" instead.

**Comment by DFreds** [comment]
I deliberately avoided adding any damage based effects because there isn't an easy using only effects to determine if the extra damage should apply. What I mean is if the extra damage should only apply to the hexed enemy, and there isn't a good way to figure that out. However, if you want to add Hex as a custom effect anyway, it should be pretty easy.

Create a new effect with this setup

```
data.bonuses.msak.damage     ADD     +1d6
data.bonuses.mwak.damage     ADD     +1d6
data.bonuses.rsak.damage     ADD     +1d6
data.bonuses.rwak.damage     ADD     +1d6

OR

data.bonuses.All-Damage   ADD   +1d6
```

There are a ton of built-in icons in Foundry that should work with a little digging. Look under Core Data -> icons or User Data -> systems/dnd5e/icons
