### ISSUE TITLE
Fix Heroism

### ISSUE THREAD

**Issue by GhostwheelX** [DFreds/dfreds-convenient-effects#85]
With the new OverTime macro from midiQOL, I think Heroism should be fixed to grant temp hp each turn, instead of just the one time when it's applied. Shouldn't be too hard, I hope?

**Comment by DFreds** [comment]
Heroism is a bit challenging as it relies on the caster's spellcasting ability modifier. Since CE is meant to be easy to apply without the need for targeting or midi or anything (although the option is there), I need to figure out the right way to ask the user for that information. It might be a simple dialog, but that could get annoying. Not sure yet

**Comment by billytherex** [comment]
If times-up supported repeating "macro.actorUpdate" from DAE like it does for "macro.execute" and "macro.itemMacro", you'd be able to use macro.actorUpdate CUSTOM @actorUuid number "@attributes.spelldc - @attributes.prof - 8" "data.attributes.hp.temp" remove

**Comment by DFreds** [comment]
@billytherex Yeah, unfortunately this still wouldn't work quite right. If you cast it on someone, CE has no way of knowing what the caster's spellcasting modifier is. It would end up using the spellcasting modifier of whichever creature got the effect.

For instance, if Cleric A has a spellcasting modifier of +3 and casts it on Wizard B with a spellcasting modifier of +5, it'll end up applying Heroism to Wizard B correctly but it would use the +5 instead of the +3. 

I've been working with tposney on a way to resolve this, but it'll take more effort.
